services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-NotEduCo342}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-MaNoHaEduNCo342@M}
      - POSTGRES_DB=${POSTGRES_DB:-portfolio}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
